### ISSUE TITLE
Have a more/menu button on vertical lists

### ISSUE THREAD

**Issue by AlbertoElias** [Financial-Times/o-hierarchical-nav#1]
This is a question for @danskinner and @pauloneillft. I'm adding an option to make vertical lists, and I was wondering what I should do about the more/menu button? Should I just remove it from vertical lists and make vertical lists always display completely? Or maybe on smaller devices the menu should be condensed this way. What do you think?

**Comment by onishiweb** [comment]
Is this still worth looking into/following up on?

**Comment by AlbertoElias** [comment]
no, o-hierarchical-nav will be deprecated soon
