### ISSUE TITLE
`createevent` isn't a valid Modernizr test name

### ISSUE THREAD

**Issue by samgiles** [Financial-Times/o-hierarchical-nav#19]
Perhaps we should consider adding the test to Modernizr?  Although, MDN suggests `createEvent` is [deprecated and old fashioned](https://developer.mozilla.org/en-US/docs/Web/API/document.createEvent) and advocates Event constructors instead (which are also not present in Modernizr).

'https://github.com/Financial-Times/o-hierarchical-nav/blob/master/origami.json#L10'

**Comment by onishiweb** [comment]
@AlbertoElias did this ever get looked at?

**Comment by AlbertoElias** [comment]
no, but o-hierarchical-nav will be deprecated soon
