### ISSUE TITLE
"Collapse all elements if the user clicks outside the nav" — undesirable behaviour?

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/o-hierarchical-nav#41]
See: https://github.com/Financial-Times/o-hierarchical-nav/blob/master/src/js/Nav.js#L241

When the user clicks anywhere on the page, the (open) navigation menu closes. I assert that this is undesirable, because in this scenario the user is reviewing each submenu page in a section, and doesn't want to keep clicking the parent in order to access the next submenu item. 

A solution might be to delete that behaviour, and/or add a configuration flag to disable/enable it.

![image](https://cloud.githubusercontent.com/assets/224547/8182071/6d750572-1423-11e5-81ff-6b7d872d2eaa.png)
Above: Clicking anywhere on the page causes the submenu to collapse.

**Comment by kaelig** [comment]
This behaviour is desirable in horizontal navigations because sub menus are dropdowns.

But you bring a very good point when it comes to vertical navs.

We could have this behaviour turned on by default and make it easy to disable through a data attribute.

Thoughts?

**Comment by AlbertoElias** [comment]
Agreed. Should I implement it?

**Comment by gvonkoss** [comment]
Closing this as it is no longer relevant.
