### ISSUE TITLE
Clarify JS instantiation documentation

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-hierarchical-nav#43]
The JS part of the documentation is deemed confusing.

See https://github.com/Financial-Times/o-hierarchical-nav#javascript-instantiation

**Comment by kaelig** [comment]
Thanks to @Thurst-ft and @adambraimbridge

**Comment by adambraimbridge** [comment]
To clarify:  I tried blindly copy-pasting the first snippet, and it didn't work ...
```javascript
var oHierarchicalNav = require('o-hierarchical-nav');
var nav = document.querySelector('.o-hierarchical-nav');
var hierarchicalNav = new oHierarchicalNav(nav);
```
... Then I tried blindly copy-pasting the second snippet, and it didn't work ...
```javascript
document.addEventListener("DOMContentLoaded", function() {
    document.dispatchEvent(new CustomEvent('o.DOMContentLoaded'));
});
```

Then I tried using my brain, and got it to work (something) like this:
```javascript
require('o-hierarchical-nav');
document.dispatchEvent(new CustomEvent('o.DOMContentLoaded'));
```

**Comment by adambraimbridge** [comment]
Oh, and it's a minor point but I got confused between "instantiation" and "initialisation", because I didn't know they mean the same thing.

**Comment by triblondon** [comment]
They are subtly different, actually.

* *instantiate* means to create something substantial from something theoretical, in practice, it means running a constructor function to create an object, which is then referred to as an **instance**. Typical example `var shadow = new Dog()`
* *initialise* means to start up, generally used to refer to the initial setting of variables or an object/module configuration.

Many origami modules are static, so you can't construct an instance from them. This one you can, so your code `new oHierarchicaNav(element)` is an instantiation.

However, firing o.DomContentLoaded instead, which ultimately achieves the same thing, is something you could reasonably regard as initalisation.

Perhaps it's best to see instantiation as a specific type of initialisation.

That very first code sample in your OP should work. Hopefully Alberto can find out why it doesn't.
