### ISSUE TITLE
Cannot read property 'hasAttribute' of null

### ISSUE THREAD

**Issue by luke-venn-ft** [Financial-Times/o-hierarchical-nav#44]
If you have no nodes with the 'data-more' attribute you get a 'Cannot read property 'hasAttribute' of null' error from the 'isMegaDropdownControl' function. This is because it is called from line 29 without a null check - I would suggest the null check be added to the 'isMegaDropdownControl' function so that it covers all possible calls.

**Comment by AlbertoElias** [comment]
Would you mind making a quick pr? :)

**Comment by luke-venn-ft** [comment]
Just done it :)

> On 14 Jul 2015, at 13:14, Alberto Elias <notifications@github.com> wrote:
> 
> Would you mind making a quick pr? :)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Financial-Times/o-hierarchical-nav/issues/44#issuecomment-121218195>.
> 


-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by kaelig** [comment]
Looks like this is fixed. Thanks!
