### ISSUE TITLE
Responsive re-order of items

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-hierarchical-nav#48]
Items relegated to the dropdown on small screens should be ordered using these criterias:

1. priority
2. original DOM order

(at the moment they are in inverse DOM order)

In http://build.origami.ft.com/files/o-hierarchical-nav@2.0.5/demos/responsive-nav.html:

![screenshot 2015-08-05 13 47 19](https://cloud.githubusercontent.com/assets/85783/9085874/a50a1186-3b78-11e5-8d9b-51be397ee878.png)

![screenshot 2015-08-05 13 38 15](https://cloud.githubusercontent.com/assets/85783/9085875/a8bd1bb6-3b78-11e5-8985-301167eecea4.png)

Expected:

- Item 3
- Item 5
- Item 1
- Item 4
- Item 2

Thanks to James Webb and Markit.com for reporting this issue.

**Comment by AlbertoElias** [comment]
Why is it wrong? item 2 has the most priority, so it goes first. Then 1 and 4 have the same, and 1 is first in the dom, so it comes out first, and then 3 and 5 have the same, but 3 is first in the dom, so it comes out first

**Comment by kaelig** [comment]
Does this mean priority is actually a "weight", but not a "priority"?

For me priority 1 sounds more important than priority 2. Does this make sense?

**Comment by AlbertoElias** [comment]
That's it, that's what I'm saying. Priority 1 should come in first, then 2, then 3. So there is a bug with the priority order, but the dom order is fine. Where the are two element with the same priority, the one that's first in DOM, comes first

**Comment by kaelig** [comment]
It's really confusing because o-squishy-list works perfectly well in the demos & tests.
