### ISSUE TITLE
Core experience improvements / demos

### ISSUE THREAD

**Issue by expe** [Financial-Times/o-hierarchical-nav#53]
If JavaScript is disabled in the demos, the dropdown menus become non-functional. This can also be confusing as the dropdown arrows are still shown.

Suggest adding or improving the demos with an example of how core experience could work.

**Comment by notlee** [comment]
Hi Tom, sorry this issue you raised was never addressed. We're now deprecating `o-hierarchical-nav` in favor of [o-header-services](https://registry.origami.ft.com/components/o-header-services).
