### ISSUE TITLE
Second level nav on mobile view

### ISSUE THREAD

**Issue by petrklus** [Financial-Times/o-hierarchical-nav#60]
I am looking into secondary level nav in mobile view (under "more"). Is there any way to implement multi level view on small screen sizes? My idea would be that the the item can just "expand" in place, pushing down same-level elements.

As a experiment/hack, I've set data-o-hierarchical-nav-is-cloneable for the nav parent and it simulates the behaviour I am after.

What I would like to see is the same behaviour as elements I "pin" using priority -1:

https://jsfiddle.net/15dc51h9/1/

In the example above, the Item 5 has the mobile behaviour I would like to see - but this cannot be combined with going into the "more" area.

The nav-cloneable seems to partially resolve the issue - the missing part is that any submenu that was cloned should have its nav-level increased, as in here:

https://jsfiddle.net/15dc51h9/2/

(which works in mobile but not in desktop)

**Comment by petrklus** [comment]
After a bit of investigation, it seems that hierarchical menus work absolutely fine in the "More" menu with the correct level. Working through a fix (https://github.com/cnk-digital-solutions/o-hierarchical-nav/commit/74a2b824dcd3b91a5f066dc29d975f1aeb611586)

**Comment by AlbertoElias** [comment]
So can we close this?

**Comment by petrklus** [comment]
Yes - I've created https://github.com/Financial-Times/o-hierarchical-nav/pull/61 to suggest a fix.

**Comment by AlbertoElias** [comment]
Thanks!
