### ISSUE TITLE
[question] how to call the resize method?

### ISSUE THREAD

**Issue by petrklus** [Financial-Times/o-hierarchical-nav#63]
In our use, we intend to use the component in a container that changes its width based on scroll position (different when on top of the page or below). The issue is that the menu only seems to react to window size changes.

We would like to call the ```resize``` method to recalculate the menu size when we change the width, however, I have not found a guidance what are the best practises to do so - any recommendations?

**Comment by AlbertoElias** [comment]
I think you should just run the `#resize` instance method of the responsive nav

**Comment by petrklus** [comment]
Could you please show me an example how to use it from code running on a page? Thank you!

**Comment by AlbertoElias** [comment]
How's this? It's an example if you're using a manual build process
```js
const oHierarchicalNav = require('o-hiearchical-nav');
const myNav = new oHierarchicalNav(document.querySelector('data-o-component="o-hierarchical-nav"'));
document.querySelector('.myContainer').addEventListener('resize', () => myNav.resize());
```

**Comment by petrklus** [comment]
Thank you - that part I understand - my query is if something similar can
be achieved when using the build service and “DOM-initialised” nav.

**Comment by AlbertoElias** [comment]
You could tell the build service to not initialise and do it manually. The build service can also (ando does so by default) give you access to the module's object via a global `Origami` object it creates, so, using the default, something like this could work:

```js
const myNav = new Origami['o-hierarchical-nav'](document.querySelector('data-o-component="o-hierarchical-nav"'));
```

**Comment by petrklus** [comment]
That’s what I am after! Could you please point me to the documentation of
the Origami object?

Just tried your example on the demo page:

http://origami-buildservice-qa.herokuapp.com/v2/demos/o-hierarchical-nav@3.1.1/responsive-nav

and I do see global Origami object, with a field “o-hierarchical-nav”.
However, I cannot use the “new” keyword with it, nor can I call it as a
function as you’ve outlined above.

**Comment by AlbertoElias** [comment]
That's not a good example, because the demos use a different entry point to the JavaScript instead of using the main.js file. Maybe try that in JSBin using the module with the default entry point.

The Origami object is documented in the export parameter in the docs, and the autoinit is the autoinit  parameter.
