### ISSUE TITLE
Add bolder hover states for nav items

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/o-hierarchical-nav#76]
These are not very accessible right now, we should add hover states where the background colour of the nav item changes.

**Comment by gvonkoss** [comment]
Waiting to see if this component is a deprecation candidate, and  may require designer input.

**Comment by notlee** [comment]
Deprecating! So I'm going to close this. 

_Hello Alice 👋_

**Comment by alicebartlett** [comment]
👋
