### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-hierarchical-nav#92]
Can `o-hierarchical-nav` be deprecated in favor of [o-header-services](https://registry.origami.ft.com/components/o-header-services)? 

It appears most remaining uses of `o-hierarchical-nav` are quite old and could be replaced with [o-header-services](https://registry.origami.ft.com/components/o-header-services), now that it supports brands and has optional drop-down navigation.

An example site which uses `o-hierarchical-nav`, which we would now recommend to use `o-header-services` + `o-layout`: http://support.ft.com/

There may be a number of other uses we are unaware of so should advertise a potential deprecation.

**Comment by JakeChampion** [comment]
I think we can, yes. Let's give it a go :-)

**Comment by chee** [comment]
:fire:

**Comment by notlee** [comment]
Done!
